version: "3.9"

services:
  postgres:
    image: postgres:14-alpine
    container_name: keycloak_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: cHaNgEmE!11
    #volumes:
    #  - ./pg-data:/var/lib/postgresql/data # uncomment to persist data

  keycloak:
    image: stelzo/keycloak:16.1.1
    container_name: keycloak
    restart: unless-stopped
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: cHaNgEmE!11
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: cHaNgEmE!11
    ports:
      - 8080:8080 # http nginx
      - 9990:9990 # wildfly management console
    #volumes:
    #  - ./share:/opt/jboss/keycloak/share # optional for exchanging files
    depends_on:
      - postgres
